default_install_hook_types = ["pre-commit", "pre-push", "commit-msg"]
default_stages = ["pre-commit"]

[update]
freeze = true

[[repos]]
repo = "builtin"
hooks = [
  { id = "check-added-large-files" },
  { id = "check-vcs-permalinks" },
  { id = "trailing-whitespace" },
  { id = "end-of-file-fixer" },
  { id = "check-merge-conflict" },
  { id = "check-case-conflict" },
  { id = "mixed-line-ending", args = ["--fix=lf"] },
  { id = "check-symlinks" },
  { id = "detect-private-key" },
  { id = "check-json" },
  { id = "check-yaml" },
  { id = "check-toml" },
]

[[repos]]
repo = "https://github.com/commitizen-tools/commitizen"
rev = "db073f6e2776db0e634dc8d6c20d4123a1cab086"  # frozen: v4.18.1
hooks = [
  { id = "commitizen" },
  { id = "commitizen-branch" },
]

[[repos]]
repo = "https://github.com/astral-sh/uv-pre-commit"
rev = "6021faba75ed39152339148a1d9e51fda8e9ee2c"  # frozen: 0.12.14
hooks = [
  { id = "uv-lock" },
]

[[repos]]
repo = "https://github.com/astral-sh/ty-pre-commit"
rev = "24cb944c372f536967c7f09b62552e7221f84363"  # frozen: v0.0.81
hooks = [
  { id = "ty" },
]

[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "e8f7d69b957a30acb2c875078d5fd012de24b64c"  # frozen: v0.16.7
hooks = [
  { id = "ruff-format" },
  { id = "ruff-check", args = ["--fix"] },
]

[[repos]]
repo = "https://github.com/tombi-toml/tombi-pre-commit"
rev = "3251597d6d00583a75057ea11da9fcb66a588198"  # frozen: v1.5.5
hooks = [
  { id = "tombi-format" },
  { id = "tombi-lint" },
]
