[project]
site_name = "Python Template"
site_url = "https://keksiqc.github.io/template-pypackage/"
repo_url = "https://github.com/keksiqc/template-pypackage"
repo_name = "keksiqc/template-pypackage"
copyright = """
Copyright &copy; 2026 Keksi
"""

nav = [
  { "Home" = "index.md" },
]

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/moon"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/sun"
toggle.name = "Switch to light mode"
