[project]
name = {{ cookiecutter.project_slug | tojson }}
version = "0.1.0"
description = {{ cookiecutter.project_description | tojson }}
readme = "README.md"
requires-python = ">=3.12"
authors = [{ name = {{ cookiecutter.author_name | tojson }}, email = {{ cookiecutter.author_email | tojson }} }]
dependencies = []

[project.scripts]
{{ cookiecutter.project_slug | tojson }} = "{{ cookiecutter.package_module }}.cli:main"

[dependency-groups]
dev = [
  { include-group = "lint" },
  { include-group = "test" },
  { include-group = "tools" },
]
docs = [
  "zensical",
]
lint = [
  "ruff",
  "ty",
]
test = [
  "coverage",
  "pytest",
]
tools = [
  "commitizen",
  "prek",
]

[build-system]
requires = ["uv_build>=0.12.14,<0.13.0"]
build-backend = "uv_build"

[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "v$version"
version_scheme = "pep440"
version_provider = "uv"
update_changelog_on_bump = true
major_version_zero = true

[tool.coverage.run]
branch = true
omit = ["*/__main__.py"]
parallel = true
source = ["src"]

[tool.pytest.ini_options]
cache_dir = ".cache/pytest"
testpaths = "tests"

[tool.ruff]
cache-dir = ".cache/ruff"
line-length = 120

[tool.ruff.lint.isort]
required-imports = ["from __future__ import annotations"]
lines-after-imports = 2

[tool.tombi.files]
exclude = ["uv.lock"]
